#!/usr/bin/env python3
"""Generate a MITRE ATT&CK Navigator layer showing this repo's coverage.

Generated artifact — do not hand-edit. Regenerate with:
    python3 scripts/build_navigator.py
Load docs/attack-navigator-layer.json at https://mitre-attack.github.io/attack-navigator/
(Open Existing Layer -> Upload from local). Orange = alert tier, blue = hunt tier; score = #rules.
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_docs import load_rules  # noqa: E402  (reuse the single rule loader)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ALERT_COLOR = "#e6550d"  # orange — page on sight
HUNT_COLOR = "#3182bd"   # blue — correlate / baseline


def main():
    rules = load_rules()
    buckets = {}
    for r in rules:
        for tid in r["tech_ids"]:
            b = buckets.setdefault((tid, r["tactic"]), {"count": 0, "alert": False, "files": set()})
            b["count"] += 1
            b["alert"] = b["alert"] or (r.get("tier") == "alert")
            b["files"].add(os.path.basename(r["path"]))

    techniques = []
    for (tid, tactic), b in sorted(buckets.items()):
        techniques.append({
            "techniqueID": tid,
            "tactic": tactic,
            "score": b["count"],
            "color": ALERT_COLOR if b["alert"] else HUNT_COLOR,
            "comment": "%d rule(s): %s" % (b["count"], ", ".join(sorted(b["files"]))),
            "enabled": True,
        })

    layer = {
        "name": "AWS CloudTrail x MITRE ATT&CK coverage",
        "versions": {"attack": "16", "navigator": "4.9.5", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": ("Coverage of the ATT&CK Cloud (IaaS/AWS) matrix by the AWS CloudTrail Sigma "
                        "rules in this repo. Orange = alert tier (page on sight), blue = hunt tier "
                        "(correlate/baseline); score = number of rules. Generated by "
                        "scripts/build_navigator.py."),
        "techniques": techniques,
        "gradient": {"colors": ["#ffffff", "#3182bd"], "minValue": 0,
                     "maxValue": max((t["score"] for t in techniques), default=1)},
        "legendItems": [
            {"label": "alert tier (page on sight)", "color": ALERT_COLOR},
            {"label": "hunt tier (correlate / baseline)", "color": HUNT_COLOR},
        ],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#dddddd",
        "sorting": 3,
        "hideDisabled": False,
    }
    with open(os.path.join(ROOT, "docs", "attack-navigator-layer.json"), "w") as f:
        json.dump(layer, f, indent=2)
        f.write("\n")
    print("Navigator layer: %d technique×tactic tiles across %d tactics."
          % (len(techniques), len({t["tactic"] for t in techniques})))


if __name__ == "__main__":
    main()
