#!/usr/bin/env python3
"""Build the attack-technique coverage scorecard from the Stratus mapping + logic tests.

Generated artifact — do not hand-edit. Regenerate with:
    python3 scripts/build_scorecard.py

HONESTY: this measures COVERAGE — "how many emulatable Stratus techniques have a detecting
rule, and how many of those rules are logic-tested". It is NOT a live detection-rate / efficacy
number. Real efficacy requires detonating Stratus in a sandbox AWS account and confirming the
deployed rule fires (see docs/validation-with-stratus.md, "Live workflow"). The words
"efficacy"/"detection rate" are deliberately avoided here.
"""
import os
import re
import sys

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
STRATUS_DOC = os.path.join(ROOT, "docs", "validation-with-stratus.md")
TEST_CASES = os.path.join(ROOT, "tests", "test_cases.yaml")
RULE_RE = re.compile(r"[a-z][a-z0-9-]*/[a-z0-9-]+\.yml")


def tested_rules():
    with open(TEST_CASES) as fh:
        return {c["rule"] for c in yaml.safe_load(fh)}


def parse_stratus():
    rows = []
    for line in open(STRATUS_DOC):
        s = line.strip()
        if not s.startswith("| `aws."):
            continue
        cols = [c.strip() for c in s.strip("|").split("|")]
        technique = cols[0].strip("` ")
        rels = ["rules/" + r if not r.startswith("rules/") else r
                for r in RULE_RE.findall(cols[2])]
        rows.append((technique, rels))
    return rows


def main():
    tested = tested_rules()
    rows = parse_stratus()
    n = len(rows)
    have_rule = have_test = 0
    out_rows = []
    for technique, rels in rows:
        exists = [r for r in rels if os.path.exists(os.path.join(ROOT, r))]
        is_tested = any(r in tested for r in rels)
        if exists and is_tested:
            status, sym = "logic-tested", "✅"
            have_rule += 1
            have_test += 1
        elif exists:
            status, sym = "rule only", "🟡"
            have_rule += 1
        else:
            status, sym = "gap", "⬜"
        out_rows.append((sym, status, technique, exists))

    pct = round(100 * have_test / n) if n else 0
    color = "brightgreen" if pct >= 75 else "yellow" if pct >= 50 else "orange"
    badge = ("![Stratus coverage](https://img.shields.io/badge/Stratus%%20coverage-%d%%2F%d%%20tested-%s)"
             % (have_test, n, color))

    md = []
    md.append("# Attack-technique coverage scorecard\n")
    md.append(badge + "\n")
    md.append("Generated by `scripts/build_scorecard.py` from the "
              "[Stratus mapping](validation-with-stratus.md) and the [logic tests](../tests/). "
              "**Do not hand-edit.**\n")
    md.append("> **What this is (and isn't).** This is *coverage*: of the emulatable "
              "[Stratus Red Team](https://stratus-red-team.cloud/) AWS techniques we track, how many "
              "have a detecting rule, and how many of those rules are backed by a true-positive/benign "
              "logic test. It is **not** a live detection-rate — that requires detonating Stratus in a "
              "sandbox account (see [Live workflow](validation-with-stratus.md#live-workflow)).\n")
    md.append("## Headline\n")
    md.append("- **%d / %d** tracked Stratus techniques have a **detecting rule** (%d%%)."
              % (have_rule, n, round(100 * have_rule / n) if n else 0))
    md.append("- **%d / %d** have a **logic-tested** rule (%d%%) — the conservative number we publish."
              % (have_test, n, pct))
    md.append("- ⬜ rows are honest gaps and good first PRs.\n")
    md.append("## Per-technique\n")
    md.append("| | Status | Stratus technique | Rule(s) |")
    md.append("|---|---|---|---|")
    for sym, status, technique, exists in out_rows:
        rule_disp = ", ".join("`%s`" % r for r in exists) if exists else "—"
        md.append("| %s | %s | `%s` | %s |" % (sym, status, technique, rule_disp))
    md.append("")
    with open(os.path.join(ROOT, "docs", "coverage-scorecard.md"), "w") as f:
        f.write("\n".join(md) + "\n")

    print("Scorecard: %d/%d techniques have a rule; %d/%d logic-tested (%d%%)."
          % (have_rule, n, have_test, n, pct))
    print("README badge:\n%s" % badge)


if __name__ == "__main__":
    main()
