#!/usr/bin/env python3
"""Pre-convert every Sigma rule to ready-to-paste queries per SIEM, into dist/.

Generated artifact — do not hand-edit. Regenerate with:
    python3 scripts/build_dist.py
Requires the sigma-cli backends: log_scale (crowdstrike), kusto, splunk, elasticsearch.

Output:
    dist/<target>/<tactic>/<rule>.<ext>     one query per rule
    dist/CONVERSION_REPORT.md               per-target converted/skipped counts (+ reasons)

IMPORTANT: queries use the raw CloudTrail JSON field names (eventName, eventSource,
requestParameters.*). Your SIEM's parsed schema may differ (e.g. Sentinel's AWSCloudTrail
table uses PascalCase columns) — treat these as starting points and adjust to your ingest schema.
"""
import glob
import os
import shutil
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_behavioral import classify  # noqa: E402  (shared rule classifier)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SIGMA = os.path.join(ROOT, ".venv", "bin", "sigma")

# (backend target id, file extension, human label)
TARGETS = [
    ("log_scale", "logscale", "CrowdStrike LogScale (Next-Gen SIEM / Falcon LogScale)"),
    ("kusto", "kql", "Microsoft Sentinel / Defender Advanced Hunting (KQL)"),
    ("splunk", "spl", "Splunk (SPL)"),
    ("esql", "esql", "Elasticsearch (ES|QL)"),
]


def convert(target, rule_path):
    """Return (ok, output_or_reason)."""
    try:
        p = subprocess.run([SIGMA, "convert", "-t", target, "--without-pipeline", rule_path],
                           capture_output=True, text=True, timeout=120)
    except Exception as e:  # noqa: BLE001
        return False, "convert crashed: %s" % e
    out = "\n".join(l for l in p.stdout.splitlines()
                    if "Warning" not in l and "warn(" not in l).strip()
    if p.returncode != 0 or not out:
        err = (p.stderr or out or "no output").strip().splitlines()
        reason = next((l for l in err if l.startswith("Error:") or "not supported" in l), err[-1] if err else "unknown")
        return False, reason.replace("Error: Feature required for conversion of Sigma rule is not supported by backend: ", "")
    return True, out


def main():
    rules = sorted(glob.glob(os.path.join(ROOT, "rules", "**", "*.yml"), recursive=True))
    for target, _, _ in TARGETS:  # clean stale queries (e.g. rules now skipped as behavioral)
        d = os.path.join(ROOT, "dist", target)
        if os.path.isdir(d):
            shutil.rmtree(d)
    report = ["# dist/ conversion report\n",
              "Generated by `scripts/build_dist.py`. One query per rule, per SIEM. "
              "Queries use raw CloudTrail field names — adjust to your ingest schema.\n"]
    for target, ext, label in TARGETS:
        converted, skipped = 0, []
        for rule_path in rules:
            rel = os.path.relpath(rule_path, ROOT)
            tactic = rel.split(os.sep)[1]
            stem = os.path.splitext(os.path.basename(rule_path))[0]
            if classify(rule_path)["behavioral"]:
                skipped.append((rel, "behavioral — bare match is noise; first-seen rule in dist/behavioral/"))
                continue
            ok, payload = convert(target, rule_path)
            if ok:
                outdir = os.path.join(ROOT, "dist", target, tactic)
                os.makedirs(outdir, exist_ok=True)
                with open(os.path.join(outdir, stem + "." + ext), "w") as f:
                    f.write(payload + "\n")
                converted += 1
            else:
                skipped.append((rel, payload))
        report.append("\n## %s  (`-t %s`)\n" % (label, target))
        report.append("**%d converted**, %d skipped → `dist/%s/`\n" % (converted, len(skipped), target))
        if skipped:
            report.append("Skipped:\n")
            for rel, reason in skipped:
                report.append("- `%s` — %s" % (rel, reason))
            report.append("")
    with open(os.path.join(ROOT, "dist", "CONVERSION_REPORT.md"), "w") as f:
        f.write("\n".join(report) + "\n")
    print("dist/ built for %d targets from %d rules." % (len(TARGETS), len(rules)))


if __name__ == "__main__":
    main()
