#!/usr/bin/env python3
"""Emit a machine-readable catalog of every detection -> detections.json (repo root).

Generated artifact — do not hand-edit. Regenerate with:
    python3 scripts/build_catalog.py

Purpose: a single structured index an AI assistant or tool can consume to reason about coverage,
find the right rule, or generate a new one consistent with the repo. Deterministic (CI-verified).
"""
import glob
import json
import os

import yaml

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DIST_TARGETS = {"crowdstrike": ("log_scale", "logscale"), "kql": ("kusto", "kql"),
                "splunk": ("splunk", "spl"), "esql": ("esql", "esql")}


def events_from_detection(det):
    names, sources = [], []
    for name, block in (det or {}).items():
        if name in ("condition", "timeframe") or not isinstance(block, dict):
            continue
        if not name.startswith("selection"):
            continue
        for key, val in block.items():
            base = key.split("|")[0]
            vals = val if isinstance(val, list) else [val]
            if base == "eventName":
                names += [v for v in vals if isinstance(v, str)]
            elif base == "eventSource":
                sources += [v for v in vals if isinstance(v, str)]
    return sorted(dict.fromkeys(names)), sorted(dict.fromkeys(sources))


def main():
    detections = []
    for path in sorted(glob.glob(os.path.join(ROOT, "rules", "**", "*.yml"), recursive=True)):
        docs = [d for d in yaml.safe_load_all(open(path)) if d]
        corr = next((d for d in docs if "correlation" in d), None)
        base = next((d for d in docs if "detection" in d), None)
        main = corr or base
        if not main:
            continue
        rel = os.path.relpath(path, ROOT)
        tactic = rel.split(os.sep)[1]
        stem = os.path.splitext(os.path.basename(rel))[0]
        names, sources = events_from_detection((base or {}).get("detection", {}))
        dist = {}
        for label, (target, ext) in DIST_TARGETS.items():
            q = os.path.join("dist", target, tactic, stem + "." + ext)
            if os.path.exists(os.path.join(ROOT, q)):
                dist[label] = q
        detections.append({
            "file": rel,
            "title": main.get("title"),
            "id": main.get("id"),
            "tactic": tactic,
            "techniques": [t.split("attack.")[1].upper() for t in main.get("tags", []) if t.startswith("attack.t")],
            "tier": main.get("tier", "hunt"),
            "level": main.get("level"),
            "correlation": bool(corr),
            "eventNames": names,
            "eventSources": sources,
            "queries": dist,
        })

    catalog = {
        "meta": {
            "name": "aws-cloudtrail-attack-detections",
            "description": "Machine-readable index of AWS CloudTrail Sigma detections mapped to MITRE ATT&CK. "
                           "Generated by scripts/build_catalog.py — see docs/using-with-ai.md.",
            "logsource": {"product": "aws", "service": "cloudtrail"},
            "count": len(detections),
            "tiers": {"alert": sum(1 for d in detections if d["tier"] == "alert"),
                      "hunt": sum(1 for d in detections if d["tier"] == "hunt")},
            "query_languages": list(DIST_TARGETS.keys()),
        },
        "detections": detections,
    }
    with open(os.path.join(ROOT, "detections.json"), "w") as f:
        json.dump(catalog, f, indent=2, sort_keys=False)
        f.write("\n")
    print("Catalog: %d detections -> detections.json" % len(detections))


if __name__ == "__main__":
    main()
